version: '3.7'
services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - test_db_volume:/pgdata

volumes:
  test_db_volume: { }