version: '3.7'
services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
    ports:
      - "5432:5432" # only for debug
    volumes:
      - db_volume:/pgdata

  adminer: # only for debug
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: 'dracula'
    depends_on:
      - db
    ports:
      - "8081:8080" # only for debug

  recommender:
    build: ../recommender/src
    restart: always
    depends_on:
      - db
    ports:
      - "5003:5000"

  app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    volumes:
      - .:/opt/app/api
    ports:
      - "8070:8080"

volumes:
  db_volume: { }