@startuml
set namespaceSeparator ::

class "mobile::dto::review.dart::CreateReviewDto" {
  +int placeId
  +String content
  +int rating
  +Map<String, dynamic> toJson()
}

class "mobile::dto::review.dart::ReviewDto" {
  +int id
  +UserSummaryDto user
  +PlaceDto placeDto
  +String content
  +int rating
}

"mobile::dto::review.dart::ReviewDto" o-- "mobile::dto::user.dart::UserSummaryDto"
"mobile::dto::review.dart::ReviewDto" o-- "mobile::dto::place.dart::PlaceDto"

class "mobile::dto::review.dart::SearchForReviewsDto" {
  +int placeId
  +int page
  +Map<String, dynamic> toJson()
}

class "mobile::dto::review.dart::SearchForReviewsByUserDto" {
  +int userId
  +int page
  +Map<String, dynamic> toJson()
}

class "mobile::dto::review.dart::GetOverallReviewDto" {
  +int placeId
  +Map<String, dynamic> toJson()
}

class "mobile::dto::review.dart::OverallReviewDto" {
  +double overallRating
  +int numRatings
}

class "mobile::dto::group.dart::GroupSummaryDto" {
  +int id
  +String name
  +String imageLink
  +String description
  +MessageDto? lastSeenMessage
  +int? unreadMessageCount
  +bool isDm
  +Map<String, dynamic> toJson()
}

"mobile::dto::group.dart::GroupSummaryDto" o-- "mobile::dto::chat.dart::MessageDto"

class "mobile::dto::group.dart::CreateGroupDto" {
  +String name
  +String description
  +Uint8List image
  +Map<String, dynamic> toJson()
}

"mobile::dto::group.dart::CreateGroupDto" o-- "dart::typed_data::Uint8List"

class "mobile::dto::group.dart::RefGroupDto" {
  +int groupId
  +Map<String, dynamic> toJson()
}

class "mobile::dto::group.dart::JioFriendsDto" {
  +int groupId
  +int page
  +Map<String, dynamic> toJson()
}

class "mobile::dto::group.dart::JioToGroupDto" {
  +int userId
  +int groupId
  +Map<String, dynamic> toJson()
}

class "mobile::dto::outing.dart::CreateOutingDto" {
  +String name
  +String description
  +int groupId
  +String start
  +String end
  +String voteDeadline
  +Map<String, dynamic> toJson()
}

class "mobile::dto::outing.dart::OutingDto" {
  +int id
  +String name
  +String description
  +int groupId
  +String start
  +String end
  +List<List<OutingStepDto>> steps
  +String voteDeadline
}

class "mobile::dto::outing.dart::GetActiveOutingDto" {
  +int groupId
  +Map<String, dynamic> toJson()
}

class "mobile::dto::user.dart::CreateUserDto" {
  +String name
  +String nickname
  +String gender
  +String town
  +String firebaseToken
  +List<String?> attractions
  +List<String?> food
  +Uint8List image
  +Map<String, dynamic> toJson()
}

"mobile::dto::user.dart::CreateUserDto" o-- "dart::typed_data::Uint8List"

class "mobile::dto::user.dart::CheckUserNameResultDto" {
  +bool isUnique
}

class "mobile::dto::user.dart::UserSummaryDto" {
  +int id
  +String username
  +String name
  +String imageLink
}

class "mobile::dto::user.dart::UserProfileDto" {
  +int id
  +String username
  +String name
  +String imageLink
  +int postCount
  +int reviewCount
  +int friendCount
}

class "mobile::dto::user.dart::SearchUsersDto" {
  +int page
  +String query
  +Map<String, dynamic> toJson()
}

class "mobile::dto::user.dart::UserRefDto" {
  +int id
  +Map<String, dynamic> toJson()
}

class "mobile::dto::outing_step.dart::CreateOutingStepDto" {
  +String description
  +int outingId
  +int placeId
  +String start
  +String end
  +Map<String, dynamic> toJson()
}

class "mobile::dto::outing_step.dart::OutingStepVoteDto" {
  +bool vote
  +UserSummaryDto userSummaryDto
  {static} +List<OutingStepVoteDto> fromJsonToList()
}

"mobile::dto::outing_step.dart::OutingStepVoteDto" o-- "mobile::dto::user.dart::UserSummaryDto"

class "mobile::dto::outing_step.dart::OutingStepDto" {
  +int id
  +int outingId
  +PlaceDto place
  +String description
  +String start
  +String end
  +List<OutingStepVoteDto> outingStepVoteDtos
  {static} +List<List<OutingStepDto>> fromJsonToList()
}

"mobile::dto::outing_step.dart::OutingStepDto" o-- "mobile::dto::place.dart::PlaceDto"

class "mobile::dto::place.dart::Point" {
  +double latitude
  +double longitude
  +Map<String, dynamic> toJson()
}

class "mobile::dto::place.dart::PlaceDto" {
  +int id
  +String name
  +String about
  +String formattedAddress
  +String imageLink
  +String location
  +PlaceType placeType
  +Point position
}

"mobile::dto::place.dart::PlaceDto" o-- "mobile::dto::place.dart::PlaceType"
"mobile::dto::place.dart::PlaceDto" o-- "mobile::dto::place.dart::Point"

class "mobile::dto::place.dart::PlaceType" {
  +int index
  {static} +List<PlaceType> values
  {static} +PlaceType attraction
}

"mobile::dto::place.dart::PlaceType" o-- "mobile::dto::place.dart::PlaceType"
"dart::core::Enum" <|-- "mobile::dto::place.dart::PlaceType"

class "mobile::dto::posts.dart::PostDto" {
  +int id
  +UserSummaryDto user
  +OutingStepDto outingStep
  +String text
  +String imageLink
  +DateTime postedAt
}

"mobile::dto::posts.dart::PostDto" o-- "mobile::dto::user.dart::UserSummaryDto"
"mobile::dto::posts.dart::PostDto" o-- "mobile::dto::outing_step.dart::OutingStepDto"

class "mobile::dto::posts.dart::CreatePostDto" {
  +int outingStepId
  +String text
  +Uint8List image
  +Map<String, dynamic> toJson()
}

"mobile::dto::posts.dart::CreatePostDto" o-- "dart::typed_data::Uint8List"

class "mobile::dto::messages.dart::MessageDto" {
  +int id
  +DateTime sentAt
  +String content
  +UserSummaryDto user
}

"mobile::dto::messages.dart::MessageDto" o-- "mobile::dto::user.dart::UserSummaryDto"

class "mobile::dto::group_invite.dart::GroupInviteDto" {
  +String id
  +DateTime expiry
  +String url
  +num groupId
}

class "mobile::dto::group_invite.dart::CreateGroupInviteDto" {
  +ExpiryOption expiryOption
  +num groupId
  +Map<String, dynamic> toJson()
}

"mobile::dto::group_invite.dart::CreateGroupInviteDto" o-- "mobile::dto::group_invite.dart::ExpiryOption"

class "mobile::dto::group_invite.dart::ExpiryOption" {
  +int index
  {static} +List<ExpiryOption> values
  {static} +ExpiryOption OneHour
}

"mobile::dto::group_invite.dart::ExpiryOption" o-- "mobile::dto::group_invite.dart::ExpiryOption"
"dart::core::Enum" <|-- "mobile::dto::group_invite.dart::ExpiryOption"

class "mobile::dto::friends.dart::FriendRequestDto" {
  +UserSummaryDto from
}

"mobile::dto::friends.dart::FriendRequestDto" o-- "mobile::dto::user.dart::UserSummaryDto"

class "mobile::dto::friends.dart::FriendRequestRefDto" {
  +int userId
  +Map<String, dynamic> toJson()
}

class "mobile::dto::friends.dart::CreateFriendRequestDto" {
  +int userId
  +Map<String, dynamic> toJson()
}

class "mobile::dto::chat.dart::MessageDto" {
  +String content
  +String sentAt
  +UserSummaryDto user
}

"mobile::dto::chat.dart::MessageDto" o-- "mobile::dto::user.dart::UserSummaryDto"

class "mobile::dto::chat.dart::SendMessageDto" {
  +String content
  +int groupId
  +Map<String, dynamic> toJson()
}

class "mobile::utils::time.dart::TimeUtil" {
  {static} +String now()
  {static} +String formatForDto()
  {static} +String formatForGroup()
  {static} +String formatDateTimeForSocialPost()
  {static} +String formatForFrontend()
  {static} +DateTime parseFromDto()
}

class "mobile::utils::errors.dart::ErrorManager" {
  {static} +Future<void> showErrorMessage()
  {static} +Future<void> showError()
}

class "mobile::main.dart::App" {
  +State<App> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::main.dart::App"

class "mobile::main.dart::_AppState" {
  +AuthService auth
  +UserService userSvc
  +UserProfileDto user
  +void initState()
  +Widget build()
}

"mobile::main.dart::_AppState" o-- "mobile::services::auth.dart::AuthService"
"mobile::main.dart::_AppState" o-- "mobile::services::user.dart::UserService"
"mobile::main.dart::_AppState" o-- "mobile::dto::user.dart::UserProfileDto"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::main.dart::_AppState"

class "mobile::model::chat_message.dart::ChatMessage" {
  +String content
  +String timestamp
  +int byId
  {static} +ChatMessage fromJson()
}

class "mobile::model::outing_steps.dart::OutingStep" {
  +String name
  +String description
  +String imageUrl
  +String whenTimeStart
  +String whenTimeEnd
  +String estimatedTime
}

class "mobile::model::chat_group.dart::ChatGroup" {
  +String groupId
  +String groupName
  +String mostRecentText
  +String time
  +String photoUrl
  +String description
  +bool isMessageRead
  +List<ChatMessage> messages
  {static} +ChatGroup fromJson()
  {static} +List<ChatMessage> getChatMessages()
  +String toString()
}

class "mobile::model::group.dart::GroupSummaryInfo" {
  +int id
  +String name
  +String description
}

class "mobile::model::group.dart::GroupInfo" {
  +UserSummaryDto owner
  +List<UserSummaryDto> members
  +LocationInfo currentLocation
  +bool isInOuting()
}

"mobile::model::group.dart::GroupInfo" o-- "mobile::dto::user.dart::UserSummaryDto"
"mobile::model::group.dart::GroupInfo" o-- "mobile::model::location.dart::LocationInfo"

class "mobile::model::review_info.dart::ReviewInfo" {
  +UserSummaryDto user
  +String content
  +LocationInfo location
}

"mobile::model::review_info.dart::ReviewInfo" o-- "mobile::dto::user.dart::UserSummaryDto"
"mobile::model::review_info.dart::ReviewInfo" o-- "mobile::model::location.dart::LocationInfo"

class "mobile::model::message.dart::MessageInfo" {
  +String content
}

class "mobile::model::chat_user.dart::ChatUser" {
  +String id
  +String photoUrl
  +String displayName
  +String phoneNumber
  +String aboutMe
  {static} +ChatUser fromJson()
}

class "mobile::model::location.dart::LocationInfo" {
  +String name
  +String imageUrl
}

class "mobile::model::outing_list.dart::Outing" {
  +List<OutingStep> outingSteps
  +int currentOuting
  +String name
  +String description
  +OutingStep getOutingStep()
  +int size()
}

class "mobile::pages::social_feed.dart::SocialFeedPage" {
  +Future<Response<List<PostDto>?>> Function(int) loadPosts
  +State<SocialFeedPage> createState()
}

"mobile::pages::social_feed.dart::SocialFeedPage" o-- "null::Future<Response<List<PostDto>>> Function(int)"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::social_feed.dart::SocialFeedPage"

class "mobile::pages::social_feed.dart::_SocialFeedPageState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::social_feed.dart::_SocialFeedPageState"

class "mobile::pages::social_feed.dart::SocialFeed" {
  +Future<Response<List<PostDto>?>> Function(int) loadPosts
  +State<SocialFeed> createState()
}

"mobile::pages::social_feed.dart::SocialFeed" o-- "null::Future<Response<List<PostDto>>> Function(int)"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::social_feed.dart::SocialFeed"

class "mobile::pages::social_feed.dart::_SocialFeedState" {
  {static} +int startingPageNumber
  -PagingController<int, PostDto> _pagingController
  +void initState()
  +void dispose()
  +void loadPosts()
  +Widget build()
  +Widget noMoreItemsIndicator()
}

"mobile::pages::social_feed.dart::_SocialFeedState" o-- "infinite_scroll_pagination::src::core::paging_controller.dart::PagingController<int, PostDto>"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::social_feed.dart::_SocialFeedState"

class "mobile::pages::social_post.dart::SocialPost" {
  +PostDto post
  +OutingService outingSvc
  +String formatHeaderContent()
  +Widget buildHeader()
  +Widget buildPicture()
  +Widget buildContent()
  +Widget buildText()
  +Widget build()
}

"mobile::pages::social_post.dart::SocialPost" o-- "mobile::dto::posts.dart::PostDto"
"mobile::pages::social_post.dart::SocialPost" o-- "mobile::services::outing.dart::OutingService"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "mobile::pages::social_post.dart::SocialPost"

class "mobile::pages::find_place.dart::FindPlaceWidget" {
  +State<FindPlaceWidget> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::find_place.dart::FindPlaceWidget"

class "mobile::pages::find_place.dart::_FindPlaceWidgetState" {
  +PlaceService placeService
  +TextEditingController queryController
  +List<PlaceDto>? results
  +int page
  +dynamic loadResults()
  +dynamic loadResultsForPage()
  +Widget build()
  +Widget buildPlaceMiniTile()
}

"mobile::pages::find_place.dart::_FindPlaceWidgetState" o-- "mobile::services::place.dart::PlaceService"
"mobile::pages::find_place.dart::_FindPlaceWidgetState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::find_place.dart::_FindPlaceWidgetState"

class "mobile::pages::create_group.dart::CreateGroupPage" {
  +UserProfileDto userProfile
  +State<CreateGroupPage> createState()
}

"mobile::pages::create_group.dart::CreateGroupPage" o-- "mobile::dto::user.dart::UserProfileDto"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::create_group.dart::CreateGroupPage"

class "mobile::pages::create_group.dart::_CreateGroupPageState" {
  +GroupService groupService
  +String createGroupName
  +String createGroupDescription
  -GlobalKey<FormFieldState<dynamic>> _groupNameKey
  -GlobalKey<FormFieldState<dynamic>> _groupDescKey
  -Uint8List _imageBytes
  +Size size
  +EdgeInsets textPadding
  +void initState()
  +Widget build()
  +void createGroup()
  +Widget buildCreateGroupNameTextBox()
  +Widget buildCreateGroupDescTextBox()
  +Widget buildCreateGroupConfirmationButton()
  +Widget buildUserImagePicker()
}

"mobile::pages::create_group.dart::_CreateGroupPageState" o-- "mobile::services::group.dart::GroupService"
"mobile::pages::create_group.dart::_CreateGroupPageState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormFieldState<dynamic>>"
"mobile::pages::create_group.dart::_CreateGroupPageState" o-- "dart::typed_data::Uint8List"
"mobile::pages::create_group.dart::_CreateGroupPageState" o-- "dart::ui::Size"
"mobile::pages::create_group.dart::_CreateGroupPageState" o-- "flutter::src::painting::edge_insets.dart::EdgeInsets"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::create_group.dart::_CreateGroupPageState"

class "mobile::pages::home.dart::HomePage" {
  +UserProfileDto userProfile
  +State<HomePage> createState()
}

"mobile::pages::home.dart::HomePage" o-- "mobile::dto::user.dart::UserProfileDto"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::home.dart::HomePage"

class "mobile::pages::home.dart::_HomePageWidgetState" {
  -int _selectedIndex
  +int currentIndex
  +PostService postService
  -void _onItemTapped()
  +void initState()
  +Future<Response<List<PostDto>?>> loadPosts()
  +Widget getPage()
  +Widget build()
}

"mobile::pages::home.dart::_HomePageWidgetState" o-- "mobile::services::posts.dart::PostService"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::home.dart::_HomePageWidgetState"

class "mobile::pages::take_picture_screen.dart::TakePictureScreen" {
  +CameraDescription camera
  +State<TakePictureScreen> createState()
}

"mobile::pages::take_picture_screen.dart::TakePictureScreen" o-- "camera_platform_interface::src::types::camera_description.dart::CameraDescription"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::take_picture_screen.dart::TakePictureScreen"

class "mobile::pages::take_picture_screen.dart::_TakePictureScreenState" {
  -CameraController _controller
  -Future<void> _initializeControllerFuture
  +void initState()
  +void dispose()
  +Widget build()
}

"mobile::pages::take_picture_screen.dart::_TakePictureScreenState" o-- "camera::src::camera_controller.dart::CameraController"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::take_picture_screen.dart::_TakePictureScreenState"

class "mobile::pages::place_profile_page.dart::PlaceProfilePage" {
  {static} +int MAX_RATING
  +PlaceDto place
  +State<PlaceProfilePage> createState()
}

"mobile::pages::place_profile_page.dart::PlaceProfilePage" o-- "mobile::dto::place.dart::PlaceDto"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::place_profile_page.dart::PlaceProfilePage"

class "mobile::pages::place_profile_page.dart::_PlaceProfilePageState" {
  +ReviewService reviewService
  +OverallReviewDto? overallReviewDto
  +List<ReviewDto> reviews
  +int page
  +TextEditingController textController
  -GlobalKey<FormState> _formKey
  {static} +double EMPTY_RATING
  -double _rating
  {static} +TextStyle OVERALL_RATING_STYLE
  {static} +TextStyle NUM_RATINGS_STYLE
  +Size size
  +void initState()
  +dynamic getOverallReview()
  +dynamic loadReviews()
  +Widget build()
  +Widget buildAboutPlace()
  +Widget buildContent()
  +Widget buildReviewsList()
  +Widget buildReviewListTile()
  +Widget buildReviewDialog()
  +Widget buildButtonBar()
  +Widget buildNavigationButtons()
  +Widget buildWriteReviewButton()
  +Widget buildReviewForm()
  +Future<bool> submitReview()
  +Widget buildEmptyContentWidget()
  +Widget buildRatingWidget()
  +Widget buildRatingBar()
}

"mobile::pages::place_profile_page.dart::_PlaceProfilePageState" o-- "mobile::services::reviews.dart::ReviewService"
"mobile::pages::place_profile_page.dart::_PlaceProfilePageState" o-- "mobile::dto::review.dart::OverallReviewDto"
"mobile::pages::place_profile_page.dart::_PlaceProfilePageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"mobile::pages::place_profile_page.dart::_PlaceProfilePageState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"mobile::pages::place_profile_page.dart::_PlaceProfilePageState" o-- "flutter::src::painting::text_style.dart::TextStyle"
"mobile::pages::place_profile_page.dart::_PlaceProfilePageState" o-- "dart::ui::Size"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::place_profile_page.dart::_PlaceProfilePageState"

class "mobile::pages::friend_components.dart::FriendComponents" {
  {static} +Widget buildFriendTile()
}

class "mobile::pages::groups_page.dart::GroupsPage" {
  +State<GroupsPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::groups_page.dart::GroupsPage"

class "mobile::pages::groups_page.dart::_GroupsPageState" {
  +GroupService groupService
  +UserService userService
  +List<GroupSummaryDto> allGroupDtos
  +List<GroupSummaryDto> currentGroupDtos
  +List<ChatGroup> allGroups
  +List<ChatGroup> groups
  +UserProfileDto userProfile
  +int sortFunction()
  +void initState()
  +void dispose()
  +void loadUserInfo()
  +void updateGroups()
  +Widget build()
  +Widget buildHeader()
  +Widget buildSearchBar()
  -void _runFilter()
  +Widget createAddGroupButton()
  +Widget buildGroups()
}

"mobile::pages::groups_page.dart::_GroupsPageState" o-- "mobile::services::group.dart::GroupService"
"mobile::pages::groups_page.dart::_GroupsPageState" o-- "mobile::services::user.dart::UserService"
"mobile::pages::groups_page.dart::_GroupsPageState" o-- "mobile::dto::user.dart::UserProfileDto"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::groups_page.dart::_GroupsPageState"

class "mobile::pages::view_all_outings.dart::ViewAllOutingsPage" {
  +List<OutingDto> pastOutings
  +State<ViewAllOutingsPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::view_all_outings.dart::ViewAllOutingsPage"

class "mobile::pages::view_all_outings.dart::_ViewAllOutingsPageState" {
  +Widget build()
  +dynamic fmtDate()
  +DateTime pdate()
  +Widget buildOutingCard()
}

"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::view_all_outings.dart::_ViewAllOutingsPageState"

class "mobile::pages::friends_page.dart::FriendsPage" {
  +int userId
  +State<FriendsPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::friends_page.dart::FriendsPage"

class "mobile::pages::friends_page.dart::_FriendsPageState" {
  +FriendService friendService
  -List<UserSummaryDto> _friends
  +StreamSubscription<dynamic>? friendRequestSubscriber
  +int currentPage
  +void initState()
  +void dispose()
  -void _loadFriends()
  +Widget build()
  +Widget buildFriendRequestsButton()
  +Widget buildAddFriendButton()
  -void _navigateAndRefresh()
  +Widget buildNoFriendsWidget()
  +Widget buildFriendsList()
}

"mobile::pages::friends_page.dart::_FriendsPageState" o-- "mobile::services::friends.dart::FriendService"
"mobile::pages::friends_page.dart::_FriendsPageState" o-- "dart::async::StreamSubscription<dynamic>"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::friends_page.dart::_FriendsPageState"

class "mobile::pages::friends_page.dart::FriendSearch" {
  +UserService userService
  +FriendService friendService
  +List<UserSummaryDto> results
  {static} +String pending
  {static} +String isSameUser
  {static} +String friendReqExists
  +List<Widget>? buildActions()
  +Widget? buildLeading()
  +Widget buildResults()
  +Widget buildErrorResults()
  +Widget buildNoResults()
  +Widget buildSearchResults()
  +void searchFriends()
  +Widget buildSuggestions()
  +Widget buildUserListTile()
  +Widget buildUserRequestDialog()
  +void sendFriendRequest()
  +void triggerSnackBar()
  +Widget buildUserAvatar()
}

"mobile::pages::friends_page.dart::FriendSearch" o-- "mobile::services::user.dart::UserService"
"mobile::pages::friends_page.dart::FriendSearch" o-- "mobile::services::friends.dart::FriendService"
"flutter::src::material::search.dart::SearchDelegate" <|-- "mobile::pages::friends_page.dart::FriendSearch"

class "mobile::pages::group_chat_page.dart::GroupChatPage" {
  +GroupSummaryDto chatGroup
  +UserProfileDto userProfile
  +State<GroupChatPage> createState()
}

"mobile::pages::group_chat_page.dart::GroupChatPage" o-- "mobile::dto::group.dart::GroupSummaryDto"
"mobile::pages::group_chat_page.dart::GroupChatPage" o-- "mobile::dto::user.dart::UserProfileDto"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::group_chat_page.dart::GroupChatPage"

class "mobile::pages::group_chat_page.dart::_GroupChatPageState" {
  +MessageService messageService
  +OutingService outingService
  +GroupService groupService
  +List<MessageDto> messages
  +OutingDto? activeOuting
  +List<OutingDto> outings
  +ExpiryOption expiryOption
  +List<UserSummaryDto> groupMembers
  +ScrollController scrollController
  +StreamSubscription<dynamic>? messagesForGroupSub
  +StreamSubscription<dynamic>? membersForGroupSub
  {static} +String ABOUT
  {static} +String SEE_PAST_OUTINGS
  {static} +String INVITE_LINK
  {static} +String JIO
  {static} +String KICK
  {static} +String LEAVE
  +void initState()
  +void dispose()
  +void updateMessages()
  +void updateMembers()
  +Future<Response<List<UserSummaryDto>?>> getGroupMembers()
  +Widget build()
  +Widget buildPage()
  +AppBar buildAppBar()
  +Widget buildGroupProfileDialog()
  +Widget buildGroupMemberList()
  +void handleProfile()
  +Widget buildGroupTitle()
  +UserSummaryDto getFriend()
  +Widget buildMenuOptions()
  +List<PopupMenuItem<String>> buildPopUpMenuItems()
  +Widget buildCreateGroupInviteWidget()
  +Widget buildJioGroupWidget()
  +void createGroupInvite()
  +void viewPastOutings()
  +void sendMessage()
}

"mobile::pages::group_chat_page.dart::_GroupChatPageState" o-- "mobile::services::message.dart::MessageService"
"mobile::pages::group_chat_page.dart::_GroupChatPageState" o-- "mobile::services::outing.dart::OutingService"
"mobile::pages::group_chat_page.dart::_GroupChatPageState" o-- "mobile::services::group.dart::GroupService"
"mobile::pages::group_chat_page.dart::_GroupChatPageState" o-- "mobile::dto::outing.dart::OutingDto"
"mobile::pages::group_chat_page.dart::_GroupChatPageState" o-- "mobile::dto::group_invite.dart::ExpiryOption"
"mobile::pages::group_chat_page.dart::_GroupChatPageState" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"mobile::pages::group_chat_page.dart::_GroupChatPageState" o-- "dart::async::StreamSubscription<dynamic>"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::group_chat_page.dart::_GroupChatPageState"

class "mobile::pages::create_outing_page.dart::CreateOutingPage" {
  +int groupId
  +State<CreateOutingPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::create_outing_page.dart::CreateOutingPage"

class "mobile::pages::create_outing_page.dart::_CreateOutingPageState" {
  +String outingName
  +String outingDesc
  +DateTimeRange? range
  +DateTime? voteDeadline
  +OutingService outingService
  -GlobalKey<FormFieldState<dynamic>> _nameKey
  -GlobalKey<FormFieldState<dynamic>> _descKey
  +OutingDto outing
  +EdgeInsets textPadding
  +Icon before
  +Icon next
  +Widget build()
  +Widget buildFirstPage()
  +Widget buildOutingNameTextBox()
  +Widget buildSelectVoteDeadlineButton()
  +Widget buildOutingDescriptionTextBox()
  +Widget buildDateRangeButton()
  +Widget buildCreateOutingButton()
  +Future<void> createOuting()
}

"mobile::pages::create_outing_page.dart::_CreateOutingPageState" o-- "flutter::src::material::date.dart::DateTimeRange"
"mobile::pages::create_outing_page.dart::_CreateOutingPageState" o-- "mobile::services::outing.dart::OutingService"
"mobile::pages::create_outing_page.dart::_CreateOutingPageState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormFieldState<dynamic>>"
"mobile::pages::create_outing_page.dart::_CreateOutingPageState" o-- "mobile::dto::outing.dart::OutingDto"
"mobile::pages::create_outing_page.dart::_CreateOutingPageState" o-- "flutter::src::painting::edge_insets.dart::EdgeInsets"
"mobile::pages::create_outing_page.dart::_CreateOutingPageState" o-- "flutter::src::widgets::icon.dart::Icon"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::create_outing_page.dart::_CreateOutingPageState"

class "mobile::pages::outing_page.dart::OutingPage" {
  +OutingDto outing
  +bool isActive
  +State<OutingPage> createState()
}

"mobile::pages::outing_page.dart::OutingPage" o-- "mobile::dto::outing.dart::OutingDto"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::outing_page.dart::OutingPage"

class "mobile::pages::outing_page.dart::_OutingPageState" {
  +int currentVote
  +OutingDto outing
  +bool isActive
  +UserProfileDto thisUser
  +UserService userSvc
  +OutingService outingSvc
  +DateTime currentTime
  +bool showVoting
  +StreamSubscription<dynamic>? timerWaitStream
  +StreamSubscription<dynamic>? actingOutingChangeSub
  +double bottomPadding
  {static} +TextStyle titleStyle
  +void initState()
  +void updateShowVoting()
  +void dispose()
  +dynamic fmtDate()
  +DateTime pdate()
  +Widget buildOutingStepHelp()
  +Widget build()
  +Widget buildVoteDeadlineTimeline()
  +Widget buildOutingStepTimelineTileConflicts()
  +String fmtDateTime()
  +String fmtTime()
  +String dur()
  +String durTill()
  +Widget buildOutingStepTimelineTileNoConflicts()
  +Widget buildVotePart()
  +Widget buildOutingStepCard()
  +Widget buildBottomComponent()
  +Widget buildOutingStepListTileComponent()
  +Widget buildPlaceAddressListTileComponent()
  +Widget buildPlaceImageListTileComponent()
  +Widget buildNotYet()
  +Widget buildInProgressPart()
  +Widget buildStatusPart()
  +Future<void> createPost()
  +Widget buildCompletedPart()
  +Widget buildVoteCompletePart()
  +Widget buildOutingStepTimelineTile()
}

"mobile::pages::outing_page.dart::_OutingPageState" o-- "mobile::dto::outing.dart::OutingDto"
"mobile::pages::outing_page.dart::_OutingPageState" o-- "mobile::dto::user.dart::UserProfileDto"
"mobile::pages::outing_page.dart::_OutingPageState" o-- "mobile::services::user.dart::UserService"
"mobile::pages::outing_page.dart::_OutingPageState" o-- "mobile::services::outing.dart::OutingService"
"mobile::pages::outing_page.dart::_OutingPageState" o-- "dart::async::StreamSubscription<dynamic>"
"mobile::pages::outing_page.dart::_OutingPageState" o-- "flutter::src::painting::text_style.dart::TextStyle"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::outing_page.dart::_OutingPageState"

class "mobile::pages::dev_panel.dart::DevPanelPage" {
  +State<DevPanelPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::dev_panel.dart::DevPanelPage"

class "mobile::pages::dev_panel.dart::_DevPanelPageState" {
  +AuthService auth
  +UserService user
  +DevPanelService devPanel
  +void initState()
  +Widget build()
  +Widget authWidget()
  +Widget authLoginWidget()
  +Widget authInfoWidget()
}

"mobile::pages::dev_panel.dart::_DevPanelPageState" o-- "mobile::services::auth.dart::AuthService"
"mobile::pages::dev_panel.dart::_DevPanelPageState" o-- "mobile::services::user.dart::UserService"
"mobile::pages::dev_panel.dart::_DevPanelPageState" o-- "mobile::services::dev_panel.dart::DevPanelService"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::dev_panel.dart::_DevPanelPageState"

class "mobile::pages::create_outing_step_page.dart::CreateOutingStepPage" {
  +OutingDto outing
  +PlaceDto? recentPlace
  +State<CreateOutingStepPage> createState()
}

"mobile::pages::create_outing_step_page.dart::CreateOutingStepPage" o-- "mobile::dto::outing.dart::OutingDto"
"mobile::pages::create_outing_step_page.dart::CreateOutingStepPage" o-- "mobile::dto::place.dart::PlaceDto"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::create_outing_step_page.dart::CreateOutingStepPage"

class "mobile::pages::create_outing_step_page.dart::_CreateOutingStepPageState" {
  +String stepDesc
  +DateTime? date
  +TimeRange? timeRange
  +PlaceDto? place
  +OutingService outingService
  +PlaceService placeService
  -GlobalKey<FormFieldState<dynamic>> _descKey
  +EdgeInsets defaultMargin
  {static} +String ERROR_STATUS
  {static} +String ERROR_FINDING
  +List<PlaceDto> foodSuggestions
  +List<PlaceDto> attractionSuggestions
  {static} +double title_gap
  +void initState()
  +dynamic initGeolocator()
  +Widget build()
  +Widget buildFirstPage()
  +Widget buildOutingDescriptionTextBox()
  +Widget buildPlaceSelectionButton()
  +Widget buildSelectPlaceCard()
  +Widget buildChosenPlaceCard()
  +Widget buildSuggestionButton()
  +Widget buildFutureRecommender()
  +Future<Response<List<PlaceDto>?>> getSuggestions()
  +Widget showErrorDialog()
  +Widget buildSuggestionDialog()
  +Widget searchChoosePlaceDialog()
  +dynamic fmtDate()
  +Widget buildDatetimeRangeButton()
  +Widget buildCreateOutingStepButton()
  +Future<void> createOutingStep()
}

"mobile::pages::create_outing_step_page.dart::_CreateOutingStepPageState" o-- "time_range_picker::src::utils.dart::TimeRange"
"mobile::pages::create_outing_step_page.dart::_CreateOutingStepPageState" o-- "mobile::dto::place.dart::PlaceDto"
"mobile::pages::create_outing_step_page.dart::_CreateOutingStepPageState" o-- "mobile::services::outing.dart::OutingService"
"mobile::pages::create_outing_step_page.dart::_CreateOutingStepPageState" o-- "mobile::services::place.dart::PlaceService"
"mobile::pages::create_outing_step_page.dart::_CreateOutingStepPageState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormFieldState<dynamic>>"
"mobile::pages::create_outing_step_page.dart::_CreateOutingStepPageState" o-- "flutter::src::painting::edge_insets.dart::EdgeInsets"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::create_outing_step_page.dart::_CreateOutingStepPageState"

class "mobile::pages::sign_in.dart::SignInPage" {
  +State<SignInPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::sign_in.dart::SignInPage"

class "mobile::pages::sign_in.dart::_SignInPageState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::sign_in.dart::_SignInPageState"

class "mobile::pages::sign_in.dart::GoogleSignIn" {
  +GoogleSignInState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::sign_in.dart::GoogleSignIn"

class "mobile::pages::sign_in.dart::GoogleSignInState" {
  +bool isLoading
  +AuthService auth
  +UserService userSvc
  +void initState()
  +Widget build()
}

"mobile::pages::sign_in.dart::GoogleSignInState" o-- "mobile::services::auth.dart::AuthService"
"mobile::pages::sign_in.dart::GoogleSignInState" o-- "mobile::services::user.dart::UserService"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::sign_in.dart::GoogleSignInState"

class "mobile::pages::sign_up.dart::SignUpPage" {
  +State<SignUpPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::sign_up.dart::SignUpPage"

class "mobile::pages::sign_up.dart::Debouncer" {
  +int milliseconds
  -Timer? _timer
  +dynamic run()
}

"mobile::pages::sign_up.dart::Debouncer" o-- "dart::async::Timer"

class "mobile::pages::sign_up.dart::_SignUpPageState" {
  -int _formIndex
  +MiscService misc
  +UserService user
  +AuthService auth
  +List<String> towns
  +List<String> genders
  +List<String> attractionTags
  +List<String> foodTags
  +Icon before
  +Icon next
  -Debouncer _usernameDebouncer
  -String? _usernameError
  -String _name
  -String _username
  -String _gender
  -String _town
  -Uint8List _imageBytes
  -List<String?> _attractions
  -List<String?> _food
  +bool attractionsFilledIn
  +bool foodFilledIn
  +bool isFilledIn
  +FutureGroup<Response<List<String>?>> futureGroup
  +Future<Response<List<String>?>> townList
  +Future<Response<List<String>?>> genderList
  +Future<Response<List<String>?>> foodList
  +Future<Response<List<String>?>> attractionList
  +void initState()
  +void refresh()
  +Widget build()
  +void checkStatus()
  +void initializeLateVariables()
  +Widget futureBuilderWelcomePage()
  +Widget buildWelcomePage()
  +Widget buildAccountDetails()
  +Widget buildUserProfile()
  +Widget buildUserImagePickerPage()
  +Widget buildConfirmationPage()
  +Widget buildConfirmationUserDetails()
  +Widget buildAttractionsConfirmationBox()
  +Widget buildAttractionsChipsDisplay()
  +Widget buildFoodConfirmationBox()
  +Widget buildFoodChipsDisplay()
  +void registerUser()
  +Widget buildConfirmationButton()
}

"mobile::pages::sign_up.dart::_SignUpPageState" o-- "mobile::services::misc.dart::MiscService"
"mobile::pages::sign_up.dart::_SignUpPageState" o-- "mobile::services::user.dart::UserService"
"mobile::pages::sign_up.dart::_SignUpPageState" o-- "mobile::services::auth.dart::AuthService"
"mobile::pages::sign_up.dart::_SignUpPageState" o-- "flutter::src::widgets::icon.dart::Icon"
"mobile::pages::sign_up.dart::_SignUpPageState" o-- "mobile::pages::sign_up.dart::Debouncer"
"mobile::pages::sign_up.dart::_SignUpPageState" o-- "dart::typed_data::Uint8List"
"mobile::pages::sign_up.dart::_SignUpPageState" o-- "async::src::future_group.dart::FutureGroup<Response<List<String>>>"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::sign_up.dart::_SignUpPageState"

class "mobile::pages::sign_up.dart::CustomText" {
  +String tag
  +String value
  +String failure
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "mobile::pages::sign_up.dart::CustomText"

class "mobile::pages::sign_up_components::fadeindexedstack.dart::FadeIndexedStack" {
  +int index
  +List<Widget> children
  +Duration duration
  +_FadeIndexedStackState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::sign_up_components::fadeindexedstack.dart::FadeIndexedStack"

class "mobile::pages::sign_up_components::fadeindexedstack.dart::_FadeIndexedStackState" {
  -AnimationController _controller
  +void didUpdateWidget()
  +void initState()
  +void dispose()
  +Widget build()
}

"mobile::pages::sign_up_components::fadeindexedstack.dart::_FadeIndexedStackState" o-- "flutter::src::animation::animation_controller.dart::AnimationController"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::sign_up_components::fadeindexedstack.dart::_FadeIndexedStackState"
"flutter::src::widgets::ticker_provider.dart::SingleTickerProviderStateMixin" <|-- "mobile::pages::sign_up_components::fadeindexedstack.dart::_FadeIndexedStackState"

class "mobile::pages::sign_up_components::sign_up_welcome.dart::SignUpWelcome" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "mobile::pages::sign_up_components::sign_up_welcome.dart::SignUpWelcome"

class "mobile::pages::chat_components.dart::ChatComponents" {
  {static} +Color USER_MESSAGE_BACKGROUND
  {static} +Color USER_NAME
  {static} +Color OTHER_MESSAGE_BACKGROUND
  {static} +Color OTHER_NAME
  {static} +Color TEXT_COLOR
  {static} +Color TIMESTAMP_COLOR
  {static} +double verticalPadding
  {static} +Widget buildMessageList()
  {static} +Widget buildMessage()
  {static} +Widget buildUserAvatar()
  {static} +Widget buildMessageBodyComponent()
  {static} +Widget buildMessageUserComponent()
  {static} +Widget buildMessageTimestampComponent()
  {static} +Widget buildInputWidget()
}

"mobile::pages::chat_components.dart::ChatComponents" o-- "dart::ui::Color"

class "mobile::pages::friend_requests_page.dart::FriendRequestPage" {
  +int userId
  +State<FriendRequestPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::friend_requests_page.dart::FriendRequestPage"

class "mobile::pages::friend_requests_page.dart::_FriendRequestPageState" {
  +FriendService friendService
  -List<FriendRequestDto> _friendRequests
  +StreamSubscription<dynamic>? friendRequestSubscriber
  +int pageNumber
  +void initState()
  +void dispose()
  -void _loadFriendRequests()
  +Widget build()
  +Widget buildContent()
  +Widget buildGridView()
  +Widget buildFriendRequestGridViewItem()
  +void approveFriendRequest()
  +void rejectFriendRequest()
}

"mobile::pages::friend_requests_page.dart::_FriendRequestPageState" o-- "mobile::services::friends.dart::FriendService"
"mobile::pages::friend_requests_page.dart::_FriendRequestPageState" o-- "dart::async::StreamSubscription<dynamic>"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::friend_requests_page.dart::_FriendRequestPageState"

class "mobile::pages::create_post.dart::CreatePostPage" {
  +int outingStepId
  +State<CreatePostPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::create_post.dart::CreatePostPage"

class "mobile::pages::create_post.dart::_CreatePostPageState" {
  -Uint8List? _imageBytes
  +TextEditingController titleController
  +PostService postSvc
  +Widget build()
  +Widget buildTitleInputWidget()
  +Widget buildImageWidget()
  +Widget buildConfirmationWidget()
  +void obtainImage()
  +Widget buildImageChoice()
  +void showErrorSnackbar()
  +void showOkSnackbar()
}

"mobile::pages::create_post.dart::_CreatePostPageState" o-- "dart::typed_data::Uint8List"
"mobile::pages::create_post.dart::_CreatePostPageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"mobile::pages::create_post.dart::_CreatePostPageState" o-- "mobile::services::posts.dart::PostService"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::create_post.dart::_CreatePostPageState"

class "mobile::pages::profile_page_components::profile_header.dart::ProfileHeader" {
  {static} +Widget Function(BuildContext, UserProfileDto) getOtherProfileHeaderBuilder()
  {static} +Widget Function(BuildContext, UserProfileDto) getUserProfileHeaderBuilder()
}

class "mobile::pages::profile_page_components::profile_header.dart::ProfileHeaderWidget" {
  +UserProfileDto userProfile
  +State<ProfileHeaderWidget> createState()
}

"mobile::pages::profile_page_components::profile_header.dart::ProfileHeaderWidget" o-- "mobile::dto::user.dart::UserProfileDto"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::profile_page_components::profile_header.dart::ProfileHeaderWidget"

class "mobile::pages::profile_page_components::profile_header.dart::_ProfileHeaderWidgetState" {
  +Widget build()
  +Widget buildDivider()
  +Widget buildButton()
}

"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::profile_page_components::profile_header.dart::_ProfileHeaderWidgetState"

class "mobile::pages::profile_page_components::profile_skeleton.dart::ProfilePageSkeleton" {
  +UserProfileDto user
  +Widget Function(BuildContext, UserProfileDto) profilePictureWidgetBuilder
  +Widget Function(BuildContext, UserProfileDto) profileHeaderWidgetBuilder
  +Widget Function(BuildContext, UserProfileDto) profileContentWidgetBuilder
  +State<ProfilePageSkeleton> createState()
}

"mobile::pages::profile_page_components::profile_skeleton.dart::ProfilePageSkeleton" o-- "mobile::dto::user.dart::UserProfileDto"
"mobile::pages::profile_page_components::profile_skeleton.dart::ProfilePageSkeleton" o-- "mobile::pages::profile_page_components::profile_skeleton.dart::Widget Function(BuildContext, UserProfileDto)"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::profile_page_components::profile_skeleton.dart::ProfilePageSkeleton"

class "mobile::pages::profile_page_components::profile_skeleton.dart::_ProfilePageSkeletonState" {
  +UserService userService
  +void initState()
  +Widget build()
  +Widget buildNameWidget()
}

"mobile::pages::profile_page_components::profile_skeleton.dart::_ProfilePageSkeletonState" o-- "mobile::services::user.dart::UserService"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::profile_page_components::profile_skeleton.dart::_ProfilePageSkeletonState"

class "mobile::pages::profile_page_components::profile_content_components.dart::ProfileContent" {
  {static} +int numTabs
  {static} +Widget Function(BuildContext, UserProfileDto) getProfileContentBuilder()
  {static} +TabBar buildTabBar()
  {static} +Widget buildTabBarView()
  {static} +Future<Response<List<PostDto>?>> Function(int) loadPostsFor()
  {static} +Widget buildPostsTabChild()
  {static} +Widget buildReviewsTabChild()
  {static} +Widget Function(BuildContext, UserProfileDto) getOtherProfileContentBuilder()
}

class "mobile::pages::profile_page_components::profile_content_components.dart::ReviewFeed" {
  +UserProfileDto user
  +State<ReviewFeed> createState()
}

"mobile::pages::profile_page_components::profile_content_components.dart::ReviewFeed" o-- "mobile::dto::user.dart::UserProfileDto"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::profile_page_components::profile_content_components.dart::ReviewFeed"

class "mobile::pages::profile_page_components::profile_content_components.dart::_ReviewFeedState" {
  +ReviewService reviewService
  {static} +int startingPageNumber
  -PagingController<int, ReviewDto> _pagingController
  +void initState()
  +void dispose()
  +void loadReviews()
  +Widget build()
  +Widget noMoreItemsIndicator()
}

"mobile::pages::profile_page_components::profile_content_components.dart::_ReviewFeedState" o-- "mobile::services::reviews.dart::ReviewService"
"mobile::pages::profile_page_components::profile_content_components.dart::_ReviewFeedState" o-- "infinite_scroll_pagination::src::core::paging_controller.dart::PagingController<int, ReviewDto>"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::profile_page_components::profile_content_components.dart::_ReviewFeedState"

class "mobile::pages::profile_page_components::profile_content_components.dart::ReviewCard" {
  +ReviewDto review
  +Widget build()
  +Widget buildReviewListTile()
  +Widget buildReviewDialog()
  +Widget buildRatingBar()
}

"mobile::pages::profile_page_components::profile_content_components.dart::ReviewCard" o-- "mobile::dto::review.dart::ReviewDto"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "mobile::pages::profile_page_components::profile_content_components.dart::ReviewCard"

class "mobile::pages::profile_page_components::profile_picture.dart::ProfilePicture" {
  {static} +Widget Function(BuildContext, UserProfileDto) getUserProfilePictureBuilder()
  {static} +Widget Function(BuildContext, UserProfileDto) getOtherProfilePictureBuilder()
  {static} +Widget buildImage()
}

class "mobile::pages::profile_page.dart::ProfilePage" {
  +int userId
  +State<ProfilePage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::pages::profile_page.dart::ProfilePage"

class "mobile::pages::profile_page.dart::_ProfilePageState" {
  +UserService userService
  +Widget Function(BuildContext, UserProfileDto) profilePictureWidgetBuilder
  +Widget Function(BuildContext, UserProfileDto) profileHeaderWidgetBuilder
  +Widget Function(BuildContext, UserProfileDto) profileContentWidgetBuilder
  +void initState()
  +Future<Response<UserProfileDto?>> getUserInfo()
  +Widget build()
  +Widget buildErrorPage()
  +void initializeWidgetBuilders()
}

"mobile::pages::profile_page.dart::_ProfilePageState" o-- "mobile::services::user.dart::UserService"
"mobile::pages::profile_page.dart::_ProfilePageState" o-- "mobile::pages::profile_page_components::profile_skeleton.dart::Widget Function(BuildContext, UserProfileDto)"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::pages::profile_page.dart::_ProfilePageState"

class "mobile::pages::settings.dart::SettingsPage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "mobile::pages::settings.dart::SettingsPage"

class "mobile::services::auth.dart::AuthService" {
  -FirebaseAuth _auth
  -GoogleSignIn _googleSignIn
  +Rxn<User?> user
  +void onReady()
  +Future<User?> signInWithGoogle()
  +Future<void> logout()
}

"mobile::services::auth.dart::AuthService" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"mobile::services::auth.dart::AuthService" o-- "google_sign_in::google_sign_in.dart::GoogleSignIn"
"mobile::services::auth.dart::AuthService" o-- "get::get_rx::src::rx_types::rx_types.dart::Rxn<User>"
"get::get_state_manager::src::rx_flutter::rx_disposable.dart::GetxService" <|-- "mobile::services::auth.dart::AuthService"

class "mobile::services::group.dart::GroupService" {
  +Future<Response<List<GroupSummaryDto>?>> getGroup()
  +Future<Response<List<GroupInviteDto>?>> getGroupInvites()
  +Future<Response<GroupInviteDto?>> createGroupInvite()
  +Future<Response<void>> invalidateGroupInvite()
  +Future<Response<GroupSummaryDto?>> createGroup()
  +Future<Response<GroupInviteDto?>> getGroupInvite()
  +Future<Response<GroupSummaryDto?>> joinByInvite()
  +Future<Response<List<UserSummaryDto>?>> getAllGroupMembers()
  +Future<Response<GroupSummaryDto?>> createDM()
  +Future<Response<List<UserSummaryDto>?>> getFriendsToJio()
  +Future<Response<void>> jio()
}

"mobile::services::base_connect.dart::BaseConnect" <|-- "mobile::services::group.dart::GroupService"

class "mobile::services::base_connect.dart::BaseConnect" {
  +AuthService auth
  +GetHttpClient unauthClient
  {static} +String? token
  {static} +String server
  +T? Function(dynamic) decoderFor()
  +List<T>? Function(dynamic) decoderForList()
  +List<String>? Function(dynamic) decoderForListString()
  +bool checkBadRequest()
  +bool checkAuthenticationError()
  +void onInit()
}

"mobile::services::base_connect.dart::BaseConnect" o-- "mobile::services::auth.dart::AuthService"
"mobile::services::base_connect.dart::BaseConnect" o-- "get::get_connect::http::src::http.dart::GetHttpClient"
"get::get_connect::connect.dart::GetConnect" <|-- "mobile::services::base_connect.dart::BaseConnect"

class "mobile::services::message.dart::MessageService" {
  +Future<Response<List<MessageDto>?>> getMessages()
  +Future<Response<dynamic>> sendMessage()
}

"mobile::services::base_connect.dart::BaseConnect" <|-- "mobile::services::message.dart::MessageService"

class "mobile::services::outing.dart::OutingService" {
  +Future<Response<List<OutingDto>?>> getAllOutings()
  +Future<Response<dynamic>> createOuting()
  +Future<Response<OutingDto?>> getActiveOuting()
  +Future<Response<dynamic>> createOutingStep()
  +Future<Response<dynamic>> vote()
  +Future<Response<OutingDto?>> getOuting()
}

"mobile::services::base_connect.dart::BaseConnect" <|-- "mobile::services::outing.dart::OutingService"

class "mobile::services::user.dart::UserService" {
  +Future<Response<UserProfileDto?>> getInfo()
  +Future<Response<UserProfileDto?>> getFriendInfo()
  +Future<Response<UserSummaryDto?>> getUserInfo()
  +Future<Response<void>> create()
  +Future<Response<void>> editImage()
  +Future<Response<List<UserSummaryDto>?>> searchForFriends()
  +Future<Response<CheckUserNameResultDto?>> checkUserName()
}

"mobile::services::base_connect.dart::BaseConnect" <|-- "mobile::services::user.dart::UserService"

class "mobile::services::place.dart::PlaceService" {
  +Future<Response<List<PlaceDto>?>> search()
  +Future<Response<List<PlaceDto>?>> recommend()
}

"mobile::services::base_connect.dart::BaseConnect" <|-- "mobile::services::place.dart::PlaceService"

class "mobile::services::posts.dart::PostService" {
  +Future<Response<List<PostDto>?>> getPosts()
  +Future<Response<List<PostDto>?>> getPostsByUser()
  +Future<Response<dynamic>> create()
}

"mobile::services::base_connect.dart::BaseConnect" <|-- "mobile::services::posts.dart::PostService"

class "mobile::services::misc.dart::MiscService" {
  +Future<Response<List<String>?>> getTowns()
  +Future<Response<List<String>?>> getGenders()
  +Future<Response<List<String>?>> getFood()
  +Future<Response<List<String>?>> getAttractions()
}

"mobile::services::base_connect.dart::BaseConnect" <|-- "mobile::services::misc.dart::MiscService"

class "mobile::services::config.dart::Config" {
  +bool isDev()
  +bool isProd()
}

class "mobile::services::dev_panel.dart::DevPanelService" {
  +Future<Response<void>> addToDefaultGroups()
}

"mobile::services::base_connect.dart::BaseConnect" <|-- "mobile::services::dev_panel.dart::DevPanelService"

class "mobile::services::friends.dart::FriendService" {
  +Future<Response<List<UserSummaryDto>?>> getFriends()
  +Future<Response<dynamic>> sendFriendRequest()
  +Future<Response<List<FriendRequestDto>?>> getFriendRequests()
  +Future<Response<void>> approveFriendRequest()
  +Future<Response<void>> rejectFriendRequest()
}

"mobile::services::base_connect.dart::BaseConnect" <|-- "mobile::services::friends.dart::FriendService"

class "mobile::services::reviews.dart::ReviewService" {
  +Future<Response<void>> createReview()
  +Future<Response<List<ReviewDto>?>> getReviews()
  +Future<Response<List<ReviewDto>?>> getReviewsByUser()
  +Future<Response<OverallReviewDto?>> getOverallReview()
}

"mobile::services::base_connect.dart::BaseConnect" <|-- "mobile::services::reviews.dart::ReviewService"

class "mobile::services::session.dart::SessionService" {
  +Stream<dynamic> stream
  +Stream<dynamic> anyFriendRequest()
  +Stream<dynamic> activeOuting()
  +Stream<dynamic> anyMessage()
  +Stream<dynamic> messageUpdate()
  +Stream<dynamic> groupUpdate()
  +Stream<dynamic> groups()
  +void initConnection()
}

"mobile::services::session.dart::SessionService" o-- "dart::async::Stream<dynamic>"
"mobile::services::base_connect.dart::BaseConnect" <|-- "mobile::services::session.dart::SessionService"

class "mobile::widgets::group_display_widget.dart::GroupDisplay" {
  +GroupSummaryDto chatGroup
  +UserProfileDto userProfile
  +State<GroupDisplay> createState()
}

"mobile::widgets::group_display_widget.dart::GroupDisplay" o-- "mobile::dto::group.dart::GroupSummaryDto"
"mobile::widgets::group_display_widget.dart::GroupDisplay" o-- "mobile::dto::user.dart::UserProfileDto"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::widgets::group_display_widget.dart::GroupDisplay"

class "mobile::widgets::group_display_widget.dart::_GroupDisplayState" {
  {static} +int N
  +Widget build()
  +Widget buildGroupIcon()
  +Widget buildGroupChatHeader()
  +String firstN()
  +Widget buildTimeAgoLabel()
}

"flutter::src::widgets::framework.dart::State" <|-- "mobile::widgets::group_display_widget.dart::_GroupDisplayState"

class "mobile::widgets::recommender_dialog.dart::RecommenderDialog" {
  +List<PlaceDto> places
  +Widget build()
  +Widget buildSuggestedPlaceListTile()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "mobile::widgets::recommender_dialog.dart::RecommenderDialog"

class "mobile::widgets::profile_widget.dart::ProfileWidget" {
  +String imagePath
  +void Function() onClicked
  +State<ProfileWidget> createState()
}

"mobile::widgets::profile_widget.dart::ProfileWidget" o-- "dart::ui::void Function()"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::widgets::profile_widget.dart::ProfileWidget"

class "mobile::widgets::profile_widget.dart::_ProfileWidgetState" {
  +String imagePath
  +void initState()
  +Widget build()
  +Widget buildImage()
  +Widget buildEditIcon()
  +Widget buildCircle()
}

"flutter::src::widgets::framework.dart::State" <|-- "mobile::widgets::profile_widget.dart::_ProfileWidgetState"

class "mobile::widgets::place_image.dart::PlaceImage" {
  +String imageLink
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "mobile::widgets::place_image.dart::PlaceImage"

class "mobile::widgets::JioGroupWidget.dart::JioFriendsToGroupWidget" {
  +int groupId
  +State<JioFriendsToGroupWidget> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "mobile::widgets::JioGroupWidget.dart::JioFriendsToGroupWidget"

class "mobile::widgets::JioGroupWidget.dart::_JioFriendsToGroupWidgetState" {
  +GroupService groupService
  {static} +int startingPageNumber
  -PagingController<int, UserSummaryDto> _pagingController
  +void initState()
  +void dispose()
  +dynamic loadFriendsToJio()
  +Widget build()
  +Widget noMoreItemsIndicator()
  +Widget buildJioTile()
  +void jioToGroup()
  +void showErrorSnackbar()
}

"mobile::widgets::JioGroupWidget.dart::_JioFriendsToGroupWidgetState" o-- "mobile::services::group.dart::GroupService"
"mobile::widgets::JioGroupWidget.dart::_JioFriendsToGroupWidgetState" o-- "infinite_scroll_pagination::src::core::paging_controller.dart::PagingController<int, UserSummaryDto>"
"flutter::src::widgets::framework.dart::State" <|-- "mobile::widgets::JioGroupWidget.dart::_JioFriendsToGroupWidgetState"

abstract class "mobile::theme.dart::AppColors" {
  {static} +Color secondary
  {static} +Color accent
  {static} +Color textDark
  {static} +Color textLight
  {static} +Color textFaded
  {static} +Color iconLight
  {static} +Color iconDark
  {static} +Color textHighlight
  {static} +Color cardLight
  {static} +Color cardDark
}

"mobile::theme.dart::AppColors" o-- "dart::ui::Color"

abstract class "mobile::theme.dart::_LightColors" {
  {static} +Color background
  {static} +Color card
}

"mobile::theme.dart::_LightColors" o-- "dart::ui::Color"

abstract class "mobile::theme.dart::_DarkColors" {
  {static} +Color background
  {static} +Color card
}

"mobile::theme.dart::_DarkColors" o-- "dart::ui::Color"

abstract class "mobile::theme.dart::AppTheme" {
  {static} +Color accentColor
  {static} +VisualDensity visualDensity
  {static} +ThemeData light()
  {static} +ThemeData dark()
}

"mobile::theme.dart::AppTheme" o-- "dart::ui::Color"
"mobile::theme.dart::AppTheme" o-- "flutter::src::material::theme_data.dart::VisualDensity"


@enduml