name: ci
on: [push]
jobs:

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: './backend/go.mod'
      - name: Generate Swagger Docs
        run: go install github.com/swaggo/swag/cmd/swag@latest && swag init
      - name: Build IoC Dependencies using Wire
        run: go install github.com/google/wire/cmd/wire@latest && wire
      - run: go build

  backend_integration_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: './backend/go.mod'
      - name: Generate Swagger Docs
        run: go install github.com/swaggo/swag/cmd/swag@latest && swag init
      - name: Build IoC Dependencies using Wire
        run: go install github.com/google/wire/cmd/wire@latest && wire
      - run: go build
      - name: Run database stack
        run: docker-compose -f docker-compose.test.yml up -d
      - run: go test -tags=integration -v .\...  -count=1

  mobile:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with: 
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.0'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi